-- CreateEnum
CREATE TYPE "SCHEDULE_STATUS" AS ENUM ('UPCOMING', 'ONGOING', 'PAST');

-- AlterTable
ALTER TABLE "Schedule" ADD COLUMN     "isPriority" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "status" "SCHEDULE_STATUS" NOT NULL DEFAULT 'UPCOMING';
