-- CreateEnum
CREATE TYPE "PARTNER_STATUS" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- AlterTable
ALTER TABLE "partners" ADD COLUMN     "logo" TEXT,
ADD COLUMN     "status" "PARTNER_STATUS" NOT NULL DEFAULT 'PENDING';
